logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: TRACE
spring:
  application:
    name: Organization_System
  jpa:
    show-sql: 'true'  main:    lazy-initialization: false  profiles:     active: '${lOAD_ENVI}'    
server:
  port: '9091'


  
  
    

